### ISSUE TITLE
how to run?

### ISSUE THREAD

**Issue by acmorfe** [graham0/ginlong-wifi#3]
Hi! Good morning.
I would like to try your code on my newly commissioned Solis 5K-4G...
I know how to program, been doing it for 30 years,  but unfortunately I do not know python... yet. :(
Please help this old dog to learn new tricks.
Thanks!

**Comment by acmorfe** [comment]
I tried this,,, 
`
D:\>py read-ginlong.py
Traceback (most recent call last):
  File "read-ginlong.py", line 72, in <module>
    sock.bind((HOST, PORT))
OSError: [WinError 10049] The requested address is not valid in its context

D:\>
`
I don't know what to do.. please help.
Thanks.

**Comment by graham0** [comment]
Hi Acmorfe,

I'm afraid this won't work for 4th gen Ginlong inverters. MediaVan contacted me earlier, he had tried it with one and it looks like Ginlong have changed the way the inverters send their data. He was going to look in to it to see if a solution could be found.

My feeling is that they have encrypted the data from the inverter. This will make it very difficult to backward engineer the output from it.

As for running the python script on Windows, I have never tried it, so don't know if it will work or not. I would think you need to run it with admin rights to allow it to bind to a port. But that's academic at the moment because it won't work.

Another approach may be to scrape the info from the web page on the inverter using cURL or wget to automate the data collection. Again though this will have to be developed for the 4th gen inverter.

Hope this helps,
Graham0

**Comment by acmorfe** [comment]
Hi Graham0,
yes, that helped. thanks. :)
and thanks for the scraping idea. :+1: 

will close this issue after a few days.
